package com.kingja.trainingday.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kingja.trainingday.greendaobean.Plan;
import com.kingja.trainingday.greendaobean.PlanDay;

import com.kingja.trainingday.dao.PlanDao;
import com.kingja.trainingday.dao.PlanDayDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig planDaoConfig;
    private final DaoConfig planDayDaoConfig;

    private final PlanDao planDao;
    private final PlanDayDao planDayDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        planDaoConfig = daoConfigMap.get(PlanDao.class).clone();
        planDaoConfig.initIdentityScope(type);

        planDayDaoConfig = daoConfigMap.get(PlanDayDao.class).clone();
        planDayDaoConfig.initIdentityScope(type);

        planDao = new PlanDao(planDaoConfig, this);
        planDayDao = new PlanDayDao(planDayDaoConfig, this);

        registerDao(Plan.class, planDao);
        registerDao(PlanDay.class, planDayDao);
    }
    
    public void clear() {
        planDaoConfig.clearIdentityScope();
        planDayDaoConfig.clearIdentityScope();
    }

    public PlanDao getPlanDao() {
        return planDao;
    }

    public PlanDayDao getPlanDayDao() {
        return planDayDao;
    }

}
